# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      first-value:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'enter a number'
        # Default value if no value is explicitly provided
        # default: '0'
        # Input has to be provided for the workflow to run
        required: true
      second-value:
        description: 'enter a number'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job1:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10' 

    # Runs a single command using the runners shell
      - name: input
        run:  |
            python prime.py ${{ github.event.inputs.first-value }} ${{ github.event.inputs.first-value }}

